/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_speex_ultraman_speex */

#ifndef _Included_com_speex_ultraman_speex
#define _Included_com_speex_ultraman_speex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_speex_ultraman_speex
 * Method:    encode
 * Signature: ([S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_speex_ultraman_speex_encode
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     com_speex_ultraman_speex
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_speex_ultraman_speex_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
