/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jay_speex_Speex */

#ifndef _Included_jay_speex_Speex
#define _Included_jay_speex_Speex
#ifdef __cplusplus
extern "C" {
#endif
#undef jay_speex_Speex_DEFAULT_COMPRESSION
#define jay_speex_Speex_DEFAULT_COMPRESSION 8L
/*
 * Class:     jay_speex_Speex
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jay_speex_Speex_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     jay_speex_Speex
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jay_speex_Speex_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     jay_speex_Speex
 * Method:    decode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_jay_speex_Speex_decode
  (JNIEnv *, jobject, jbyteArray, jshortArray, jint);

/*
 * Class:     jay_speex_Speex
 * Method:    encode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_jay_speex_Speex_encode
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     jay_speex_Speex
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jay_speex_Speex_close
  (JNIEnv *, jobject);

/*
 * Class:     jay_speex_Speex
 * Method:    echo_init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jay_speex_Speex_echo_1init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jay_speex_Speex
 * Method:    echo_playback
 * Signature: ([S)I
 */
JNIEXPORT jint JNICALL Java_jay_speex_Speex_echo_1playback
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     jay_speex_Speex
 * Method:    echo_capture
 * Signature: ([S[S)I
 */
JNIEXPORT jint JNICALL Java_jay_speex_Speex_echo_1capture
  (JNIEnv *, jobject, jshortArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
